task :asdf do
  puts "This is a task"
end

require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = "features --format pretty"
end

task :sanity do
  puts "running sanity tests"
end

task :smoke do
  puts "running smoke tests"
end

task :regression do
  puts "running regression tests"
end

task :release => [:sanity, :smoke, :regression]
